config/routes.rb
Rails.application.routes.draw do
  
  devise_for :fusers
  resources :fables
  root 'fables#index'
  get 'home/About'
  get 'home/views/deviseregistrations/new'
  #get'home/firstpage'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fable.rb
class Fable < ApplicationRecord
belongs_to:fuser
end

app/models/fuser.rb
class Fuser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many:fable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fables_controller.rb
class FablesController < ApplicationController
  before_action :set_fable, only: %i[ show edit update destroy ]
  before_action :correct_fuser, only: [:edit, :update, :destroy]
  # GET /fables or /fables.json
  def index
    @fables = Fable.all
  end

  # GET /fables/1 or /fables/1.json
  def show
  end

  # GET /fables/new
  def new
    #@fable = Fable.new
    @fable=current_fuser.fable.build
  end

  # GET /fables/1/edit
  def edit
  end

  # POST /fables or /fables.json
  def create
    #@fable = Fable.new(fable_params)
@fable=current_fuser.fable.build(fable_params)
    respond_to do |format|
      if @fable.save
        format.html { redirect_to @fable, notice: "Fable was successfully created." }
        format.json { render :show, status: :created, location: @fable }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fables/1 or /fables/1.json
  def update
    respond_to do |format|
      if @fable.update(fable_params)
        format.html { redirect_to @fable, notice: "Fable was successfully updated." }
        format.json { render :show, status: :ok, location: @fable }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fables/1 or /fables/1.json
  def destroy
    @fable.destroy
    respond_to do |format|
      format.html { redirect_to fables_url, notice: "Fable was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def correct_fuser
    @fable=current_fuser.fable.find_by(id: params[:id])
 redirect_to fables_path, notice: "Not Authorised to to modify" if @fables.nil?
  
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fable
      @fable = Fable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fable_params
      params.require(:fable).permit(:first_name, :last_name, :email, :phone, :twitter , :fuser_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def firstpage

  end
  def About
    @About_me="My name is faran javed...."
     @Copy_tatti="GHAR WALON SE PAISE MUNGAWAI WARNA WEBSITE AAGE NAHIN CHALE GI."
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fables_helper.rb
module FablesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/fables/_form.html.erb
<%= form_with(model: fable) do |form| %>
  <% if fable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fable.errors.count, "error") %> prohibited this fable from being saved:</h2>

      <ul>
        <% fable.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control" , placeholder:"Last Name"%>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control" , placeholder:"Email" %>
  </div>

  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class:"form-control", placeholder:"phone" %>
  </div>

  <div class="field form-group">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, class:"form-control", placeholder:"twitter" %>
  </div>

<div class="field form-group">
    <%= form.number_field :fuser_id,id: :fable_fuser_id,
    class:"form-control", value:current_fuser.id %>
    
  </div>

  <div class="actions form-group">
  </br>
    <%= form.submit %>
  </div>
<% end %>

app/views/fables/edit.html.erb
<h1>Editing Friends </h1>

<%= render 'form', fable: @fable %>
</br>
</br>
<%= link_to 'Show', @fables_path , class:"btn btn-secondary"%> 
<%= link_to 'Back', fables_path , class:"btn btn-secondary" %>

app/views/fables/index.html.erb
<%if fuser_signed_in?%>
<h1>Our Best Friends</h1>

<table class="table table-responsive table-striped table-bordered table-hover ">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th>User_Id</th>
      <th> </th>
    </tr>
  </thead>

  <tbody>
    <% @fables.each do |fable| %>
    <%if fable.fuser==current_fuser%>
      <tr>
        <td>
          <%= link_to fable.first_name + fable.last_name, fable %>
        
            
        </td>
       
        <td><%= fable.email %></td>
        <td><%= fable.phone %></td>
        <td><%= fable.twitter %></td>
        <td><%= fable.fuser_id %></td>
        
       
        <td><%= link_to 'Delete', fable, method: :delete, data: { confirm: 'Are you sure?' } ,class:" btn btn-danger btn-sm"%></td>
      </tr>
      <%end%>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_fable_path, class:"btn btn-secondary "%>
<%else%>

<h1>Faran</h1>
<p>I love rails</p>
<p>starting </p>
<%end%>

app/views/fables/new.html.erb
<h1>Add Your New Best Friend</h1>
</br>
</br>
<%= render 'form', fable: @fable %>
</br>
</br>
<%= link_to 'Back', fables_path , class:"btn btn-secondary "%>

app/views/fables/show.html.erb
<div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2><%= @fable.first_name %></h2>
          <h2><%= @fable.last_name %></h2>

          <p><%= @fable.email %> | <%= @fable.phone %> | <%= @fable.twitter %>  | <%= @fable.fuser_id%> </p>
        <%= link_to 'Home', root_path , class:"btn btn-secondary"%>
<%= link_to 'Edit', edit_fable_path(@fable) , class:"btn btn-secondary"%> 
<%= link_to 'Back', fables_path , class:"btn btn-secondary"%>
        </div>
      </div>



</br>

app/views/home/About.html.erb
<h1>ABOUT US </h1>

<p> 
	<%= @About_me %>
</br>
	<%= @Copy_tatti %>
</p>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'FARANS RUBY' , root_path , class:"navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
        	<%=link_to "About us",home_About_path,class:"nav-link"%>
          
       
     <li class="nav-item">
          <%=link_to "Friends",fables_path,class:"nav-link"%>
          
        </li>
       
         <li class="nav-item">
          <%=link_to "New Friend",new_fable_path,class:"nav-link"%>
          
        </li>
        #copy point
        <li class="nav-item">
          <%=link_to "Sign up",new_fuser_registration_path,class:"nav-link"%>
          
        </li>
        <li class="nav-item">
          <%=link_to "Sign in",new_fuser_session_path,class:"nav-link"%>
          
        </li>
        <li class="nav-item">
          <%=link_to "Sign out",destroy_fuser_session_path, method: :delete ,  class:"nav-link"%>
          
        </li>
        <li class="nav-item">
          <%=link_to "Edit Profile",edit_fuser_registration_path,class:"nav-link"%>
          
        </li>
        #end poimt
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/firstpage.html.erb
<h1>Faran</h1>
<p>I love rails</p>
<p>starting </p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  
  <%=notice%>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <title>FARAN JD</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <br/><br/><br/>
    <%= render 'home/header' %>
    <div class="container">
      <%if notice%>
      <%=render 'layouts/alerts' %>
      <%end%>
      <br/>
    <%= yield %>
  </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>